app/models.py
from . import db
from sqlalchemy.sql import func
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255),unique = True,nullable = False)
    email = db.Column(db.String(255),unique = True,nullable = False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password = db.Column(db.String(255),nullable = False)
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'

class Posts(db.Model):
    __tablename__= 'posts'
    id = db.Column(db.Integer,primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False)
    author = db.Column(db.String(50))
    date_posted = db.Column(db.DateTime, default=db.func.current_timestamp())
    title = db.Column(db.String(50))
    post = db.Column(db.String(999))
    

    comments = db.relationship('Comment',backref='post',lazy='dynamic')
   
    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_posts(cls):
        return Posts.query.order_by(Posts.date_posted).all()

    def delete_post(self):
        db.session.delete(self)
        db.session.commit()

    
    def __repr__(self):
        return f'User {self.pitch}'

class Comment(db.Model):
    __tablename__='comments'
    
    id = db.Column(db.Integer,primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable= False)
    description = db.Column(db.Text)

    
    def __repr__(self):
        return f"Comment : id: {self.id} comment: {self.description}"


class Subscribers(db.Model):
    __tablename__ = "subscribers"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(255), unique = True, index = True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,SubmitField,TextAreaField,RadioField
from wtforms.validators import Required,Email,EqualTo
from wtforms import ValidationError


	

class CommentForm(FlaskForm):
	description = TextAreaField('',validators=[Required()])
	submit = SubmitField() 

class PostForm(FlaskForm):
    title = StringField("title",validators=[Required()])
    post = TextAreaField("post",validators=[Required()])
    author = StringField("author",validators=[Required()])
    submit = SubmitField('post blog')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config.from_object(config_options[config_name])
    # configure UploadSet
    configure_uploads(app,photos)
   

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
   
 
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
 


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import Flask, render_template, redirect, url_for, abort, request
from . import main
from ..models import Posts, Comment, User, Subscribers
from .forms import CommentForm,PostForm,UpdateProfile
from flask_login import login_required, current_user
from ..import db, photos
from ..email import mail_message

 

@main.route('/',methods = ["GET", "POST"])
def index():
    posts = Posts.get_all_posts()
    
    user=User()
    if request.method == "POST":
        subscribed = Subscribers(email = request.form.get("subs"))
        db.session.add(subscribed)
        db.session.commit()

        mail_message("Welcome to The new blogsite", 
                        "email/welcome_user", subscribed.email)
       
    
    return render_template('index.html',posts = posts)

@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/post', methods = ['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = form.post.data
        owner_id = current_user
        title = form.title.data
        author = form.author.data
        new_post = Posts(owner_id =current_user._get_current_object().id,post=post,author=author,title=title)
        new_post.save_post()
        subs = Subscribers.query.all()
        for sub in subs:
            mail_message('New blog posted', 
                            "email/welcome_user", sub.email, new_post = new_post)
            pass

        return redirect(url_for('main.index'))
    return render_template('posts.html',form=form)

@main.route('/blog/<int:id>', methods = ['GET','POST'])
@login_required
def blog(id):
    post = Posts.query.filter_by(id = id).first()
  

    
    return render_template('blog.html',post=post)




@main.route('/comment/<int:post_id>', methods = ['GET','POST'])
@login_required
def new_comment(post_id):
    form = CommentForm()
    post=Posts.query.get(post_id)
    if form.validate_on_submit():
        description = form.description.data

        new_comment = Comment(post=post,user_id = current_user._get_current_object().id, post_id = post_id)
        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('main.new_comment', post_id= post_id))
    all_comments = Comment.query.filter_by(post_id = post_id).all()
    return render_template('comment.html', form = form,comment = all_comments )

@main.route('/profile/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'images/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to Blogsite </title>
        {% endif %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/blog.html
{% extends 'base.html'%}
{% block content %}
<style>
    body{
        background-color: indianred;
    }
</style>
<div class="container">

<div class="card text-center">
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <hr>
      <p class="card-text">{{post.post}}</p>
      
      
    </div>
    <div class="card-footer text-muted">
      <b>posted on:</b>{{post.date_posted}} <br>
      <b>by:</b>{{post.author}} <br>
      <a href="{{url_for('main.new_comment',post_id = post.id)}}" class="btn btn-info">go to comments</a>
    </div>
  </div>

</div>
{% endblock %}

app/templates/comment.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% include 'navbar.html'%}
{% import 'macros.html' as macro %}

{% block content %}

<div class="container">
    <div class="wrapper" style="margin-top:100px">
            {{wtf.quick_form(form)}} 
    </div>
    <div class="row">
            {{ macro.displayComment(comment) }}
    
    
    </div>
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
<style>
    body{
        background-color: brown;
    }
    .head{
        text-align: center;
        font-weight: bold;
    }
</style>

<div class="head">
    <h2>Welcome to the new Blogsite</h2>
</div>
<div class="head text-center">
    <button class="btn btn-success"><a href="{{url_for('main.new_post')}}">post new blog</a></button>
    <br>
    <div class="row">
        <div class="col-md-3"></div>
    <form  class="col-md-6" method="POST">
        
        <input type="email" class="form-control" name="subs" placeholder="Enter your email..." required>
        <button type="submit" class="btn btn-outline-primary">subscribe</button>
    </form>
    </div>
</div>

<div class="container">
    {{ macro.display(posts) }}
</div>

{% endblock %}

app/templates/macros.html
{% macro display(posts_list) %}

    {% for post in posts_list %}
    <div class="card text-center">
        <div class="card-header">
          by:{{post.author}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{post.post|truncate(100)}}</p>
          <a href="{{url_for('main.blog', id = post.id)}}" class="btn btn-primary">read more >></a>
          
        </div>
        <div class="card-footer text-muted">
          <b>posted on:</b>{{post.date_posted.strftime('%Y-%m-%d')}}
          <a href="{{url_for('main.new_comment',post_id = post.id)}}" class="btn btn-info">comment</a>
        </div>
        
      </div>
      <br>
      
       
    {% endfor %}

{% endmacro %}

{% macro displayComment(comments) %}
<ul>
			{% if comments %}
            {% for comment in comments %}
            
            <div class="card text-center">
                <div class="card-header">
                  by:{{comment.user.username}}
                </div>
                <div class="card-body">
                
                  <p class="card-text">{{comment.description}}</p>
                  
                </div>
                <div class="card-footer text-muted">
                    <button class="btn btn-danger">delete</button>
                </div>
               
            </div>
				
				
				
			{% endfor %}
			{% else %}

			<h3>No comments for this post yet!!</h3>
			{%endif%}

	</ul>
	{% endmacro %}

app/templates/navbar.html
<ul class="nav navbar-nav navbar-right">
    {% if current_user.is_authenticated %}
    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
    {% else %}
    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
    {%endif%}
  </ul>

app/templates/posts.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% include 'navbar.html'%}

{% block content %}
<style>
	body{
		background-color: cadetblue;
	}
</style>
<div class="container">
	<br>
	<div class="wrapper">
  		{{ wtf.quick_form(form) }}
	</div>




{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

        {% if user == current_user %}
        <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
        </form>
        {% endif %}
  </div>

  <div class="col-md-4">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}